import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it, expect } from "vitest";
import { isOk } from "@mallet/shared/types";
import { parseNormalizedGeometry } from "./normalized-geometry";
import { derivePaintingQuantities } from "./derive-painting";

/**
 * The wire-contract corpus, generated BY THE SWIFT ENCODER in mallet-ios
 * (`MALLET_WRITE_WIRE_CORPUS=1 swift test --filter WireCorpusTests`, then copy
 * `WireCorpus/*.json` here). Every file is a shape the phone can legitimately put on the
 * wire — including the omitted-optional-key encodings Swift produces — and every file MUST
 * parse and derive without throwing.
 *
 * WHY: the vaulted-ceiling incident (Jul 29 2026) — Swift omits nil optionals, the schema
 * required the key, and the first real vaulted-room scan failed to save. This suite turns
 * that whole drift class into a CI failure. Never delete a corpus file to make the suite
 * pass; that is the contract breaking.
 */
const CORPUS_DIR = join(__dirname, "__fixtures__", "wire-corpus");

describe("wire-contract corpus (generated by the Swift encoder)", () => {
  const files = readdirSync(CORPUS_DIR).filter((f) => f.endsWith(".json"));

  it("has the expected corpus on disk", () => {
    expect(files.length).toBeGreaterThanOrEqual(6);
    expect(files).toContain("vaulted-ceiling-nil-area.json");
  });

  for (const file of files) {
    it(`parses and derives ${file}`, () => {
      const wire: unknown = JSON.parse(readFileSync(join(CORPUS_DIR, file), "utf8"));
      const parsed = parseNormalizedGeometry(wire);
      expect(isOk(parsed), `parse rejected ${file}: ${!parsed.ok ? parsed.error.message : ""}`).toBe(true);
      if (!isOk(parsed)) return;
      const quantities = derivePaintingQuantities(parsed.value);
      // Every kind is present for every scan — a room the scanner said nothing about still gets a
      // row, so the painter sees "not measured" rather than a silently absent line.
      expect(quantities.map((q) => q.kind)).toEqual([
        "walls_sqft",
        "ceiling_sqft",
        "soffit_sqft",
        "baseboard_lnft",
        "crown_lnft",
        "doors_count",
        "windows_count",
      ]);
      // A soffit is never derivable from a RoomPlan payload — no value AND no suggestion.
      const soffit = quantities.find((q) => q.kind === "soffit_sqft");
      expect(soffit).toEqual({ kind: "soffit_sqft", value: null, derivedValue: null, status: "needs_confirm" });
    });
  }
});
