/**
 * Unit tests for CreateTimeEntryUseCase.
 *
 * Covers:
 *  - empty workDate validation error (guard branch)
 *  - id-minted branch: id generated by IdGenerator when cmd.id is absent
 *  - id-provided branch: cmd.id is forwarded as-is without minting
 *  - happy path: create called with correct payload, ok result returned, log side-effect
 */

import { describe, it, expect } from "vitest";
import {
  asOrgId,
  asUserId,
  asJobId,
  FixedClock,
  isOk,
} from "@mallet/shared/types";
import type { IdGenerator } from "@mallet/shared/ports";
import { TimeEntry, type TimeEntryProps } from "../domain/time-entry";
import type { TimeEntryRepository } from "../domain/time-entry-repository";
import type { TimeEntryId } from "@mallet/shared/types";
import { CreateTimeEntryUseCase, type CreateTimeEntryCommand } from "./create-time-entry";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ORG = asOrgId("22222222-2222-2222-2222-222222222222");
const USER_ID = asUserId("33333333-3333-3333-3333-333333333333");
const JOB_ID = asJobId("44444444-4444-4444-4444-444444444444");
const MINTED_ID = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
const CLIENT_ID = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const baseProps = (overrides: Partial<TimeEntryProps> = {}): TimeEntryProps => ({
  id: MINTED_ID as TimeEntryId,
  orgId: ORG,
  techUserId: USER_ID,
  jobId: null,
  workDate: "2026-07-07",
  kind: "job",
  startTime: "08:00",
  endTime: "10:00",
  minutes: null,
  note: "",
  src: "manual",
  status: "draft",
  running: false,
  approvedAt: null,
  editedByUserId: null,
  createdAt: new Date("2026-07-07T08:00:00Z"),
  updatedAt: new Date("2026-07-07T08:00:00Z"),
  ...overrides,
});

const makeEntry = (overrides: Partial<TimeEntryProps> = {}): TimeEntry => {
  const result = TimeEntry.create(baseProps(overrides));
  if (!result.ok) throw new Error(`test setup: TimeEntry.create failed: ${JSON.stringify(result.error)}`);
  return result.value;
};

// ---------------------------------------------------------------------------
// Minimal in-memory fake for TimeEntryRepository
// ---------------------------------------------------------------------------

class FakeTimeEntryRepository implements TimeEntryRepository {
  readonly createCalls: Parameters<TimeEntryRepository["create"]>[0][] = [];
  private nextEntry: TimeEntry | null = null;

  /** Preload the TimeEntry the fake will return from create(). */
  willReturn(entry: TimeEntry): void {
    this.nextEntry = entry;
  }

  async create(input: Parameters<TimeEntryRepository["create"]>[0]): Promise<TimeEntry> {
    this.createCalls.push(input);
    if (!this.nextEntry) throw new Error("FakeTimeEntryRepository: call willReturn() first");
    const entry = this.nextEntry;
    this.nextEntry = null;
    return entry;
  }

  // Remaining interface methods — not exercised by create-time-entry
  async findById(): Promise<TimeEntry | null> {
    return null;
  }
  async count(): Promise<number> {
    return 0;
  }

  /** Rows the fake's list() can return — the overlap gate reads the day through this. Filtered
   *  the way the real repository filters, so a use-case querying the wrong tech or day would
   *  fetch nothing and the overlap tests would catch it. */
  readonly listRows: TimeEntry[] = [];
  /** Set to simulate a day too big for one page — the gate must refuse, not trust page 1. */
  listNextCursor: string | null = null;

  async list(
    filter: Parameters<TimeEntryRepository["list"]>[0],
  ): Promise<{ items: TimeEntry[]; nextCursor: string | null }> {
    const items = this.listRows.filter(
      (e) =>
        (filter.techUserId === undefined || e.props.techUserId === filter.techUserId) &&
        (filter.fromDate === undefined || e.props.workDate >= filter.fromDate) &&
        (filter.toDate === undefined || e.props.workDate <= filter.toDate),
    );
    return { items, nextCursor: this.listNextCursor };
  }
  async save(): Promise<void> {
    // no-op
  }
  async remove(): Promise<number> {
    return 0;
  }
  // Added with the unfinished-week guard: these fakes hold no rows, so nothing is unfinished.
  async unfinishedDates(): Promise<string[]> {
    return [];
  }

  async approveWeek(): Promise<number> {
    return 0;
  }

  // Added with the clock state machine: the use-cases under test never tap the clock, so it
  // is always idle here.
  async findOpenForTech(): Promise<TimeEntry | null> {
    return null;
  }
}

// Deterministic IdGenerator stub — always returns MINTED_ID.
const stubIds: IdGenerator = { newId: () => MINTED_ID };

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("CreateTimeEntryUseCase — workDate validation guard", () => {
  it("returns a validation error when workDate is an empty string", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: null,
      workDate: "",        // <- empty: triggers guard
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.kind).toBe("validation");
    if (result.error.kind === "validation") expect(result.error.field).toBe("workDate");
    // create() must never have been called
    expect(repo.createCalls).toHaveLength(0);
  });
});

describe("CreateTimeEntryUseCase — id-minted branch", () => {
  it("mints a new id when cmd.id is absent", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    repo.willReturn(makeEntry({ id: MINTED_ID as TimeEntryId }));

    const cmd: CreateTimeEntryCommand = {
      // id intentionally omitted
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    expect(repo.createCalls).toHaveLength(1);
    // The id forwarded to the repository must be the one minted by stubIds
    expect(repo.createCalls[0]?.id).toBe(MINTED_ID);
  });

  it("uses cmd.id when provided (does not mint)", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    repo.willReturn(makeEntry({ id: CLIENT_ID as TimeEntryId }));

    const cmd: CreateTimeEntryCommand = {
      id: CLIENT_ID,      // <- client-authored id
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    expect(repo.createCalls).toHaveLength(1);
    // The client-supplied id must reach the repository unchanged
    expect(repo.createCalls[0]?.id).toBe(CLIENT_ID);
  });
});

describe("CreateTimeEntryUseCase — happy path", () => {
  it("forwards the full payload to the repository and returns ok with the TimeEntry", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    const expectedEntry = makeEntry({
      id: MINTED_ID as TimeEntryId,
      orgId: ORG,
      techUserId: USER_ID,
      jobId: JOB_ID,
      workDate: "2026-07-07",
      kind: "travel",
      startTime: "09:00",
      endTime: "11:30",
      note: "drove to site",
      src: "clock",
      running: false,
    });
    repo.willReturn(expectedEntry);

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: JOB_ID,
      workDate: "2026-07-07",
      kind: "travel",
      startTime: "09:00",
      endTime: "11:30",
      note: "drove to site",
      src: "clock",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    if (!isOk(result)) return;

    // Returns the TimeEntry instance from the repo
    expect(result.value).toBeInstanceOf(TimeEntry);
    expect(result.value.props.workDate).toBe("2026-07-07");
    expect(result.value.props.kind).toBe("travel");
    expect(result.value.props.note).toBe("drove to site");

    // create was called exactly once
    expect(repo.createCalls).toHaveLength(1);
    const payload = repo.createCalls[0]!;
    expect(payload.orgId).toBe(ORG);
    expect(payload.techUserId).toBe(USER_ID);
    expect(payload.jobId).toBe(JOB_ID);
    expect(payload.workDate).toBe("2026-07-07");
    expect(payload.kind).toBe("travel");
    expect(payload.startTime).toBe("09:00");
    expect(payload.endTime).toBe("11:30");
    expect(payload.note).toBe("drove to site");
    expect(payload.src).toBe("clock");
    expect(payload.status).toBe("draft");
    expect(payload.running).toBe(false);
  });

  it("returns the TimeEntry returned by the repository (not a transformed copy)", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    const sentinel = makeEntry();
    repo.willReturn(sentinel);

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    if (!isOk(result)) return;
    // Same reference — not a re-wrapped copy
    expect(result.value).toBe(sentinel);
  });

  it("passes running=true and null endTime through to the repository (running timer)", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    repo.willReturn(makeEntry({ endTime: null, running: true }));

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: null,
      note: "",
      src: "timer",
      running: true,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    expect(repo.createCalls).toHaveLength(1);
    expect(repo.createCalls[0]?.endTime).toBeNull();
    expect(repo.createCalls[0]?.running).toBe(true);
    expect(repo.createCalls[0]?.src).toBe("timer");
  });
});

// ---------------------------------------------------------------------------
// The overlap gate: one person cannot be two places at once. The 12.02h Tuesday
// was Shop 10:00–22:00 plus Shop 10:37–10:38, both summed into payroll.
// ---------------------------------------------------------------------------

describe("CreateTimeEntryUseCase — one person cannot be two places at once", () => {
  const cmd = (over: Partial<CreateTimeEntryCommand> = {}): CreateTimeEntryCommand => ({
    techUserId: USER_ID,
    jobId: null,
    workDate: "2026-07-07",
    kind: "shop",
    startTime: "10:37",
    endTime: "10:38",
    note: "",
    src: "manual",
    running: false,
    ...over,
  });

  it("refuses a row inside an existing one, naming the clash", async () => {
    const repo = new FakeTimeEntryRepository();
    repo.listRows.push(makeEntry({ kind: "shop", startTime: "10:00", endTime: "22:00" }));
    const useCase = new CreateTimeEntryUseCase(repo, new FixedClock(new Date("2026-07-07T08:00:00Z")), stubIds);

    const result = await useCase.exec(cmd(), ORG);

    expect(isOk(result)).toBe(false);
    if (!isOk(result)) {
      expect(result.error.message).toContain("Overlaps Shop 10:00–22:00");
    }
    expect(repo.createCalls).toHaveLength(0);
  });

  it("refuses a row that collides with the OPEN clock segment, saying the day is still open", async () => {
    const repo = new FakeTimeEntryRepository();
    repo.listRows.push(makeEntry({ startTime: "13:00", endTime: null, running: true, src: "clock" }));
    const useCase = new CreateTimeEntryUseCase(repo, new FixedClock(new Date("2026-07-07T08:00:00Z")), stubIds);

    const result = await useCase.exec(cmd({ startTime: "14:00", endTime: "15:00" }), ORG);

    expect(isOk(result)).toBe(false);
    if (!isOk(result)) {
      expect(result.error.message).toContain("Still on the clock since 13:00");
    }
  });

  it("still creates when rows only touch", async () => {
    const repo = new FakeTimeEntryRepository();
    repo.listRows.push(makeEntry({ kind: "shop", startTime: "10:00", endTime: "22:00" }));
    repo.willReturn(makeEntry({ startTime: "08:00", endTime: "10:00" }));
    const useCase = new CreateTimeEntryUseCase(repo, new FixedClock(new Date("2026-07-07T08:00:00Z")), stubIds);

    const result = await useCase.exec(cmd({ startTime: "08:00", endTime: "10:00" }), ORG);

    expect(isOk(result)).toBe(true);
    expect(repo.createCalls).toHaveLength(1);
  });
});

// Review findings, Aug 11: the gate must not misfire on retries, inverted windows, other days,
// or a day too big for one page.
describe("CreateTimeEntryUseCase — overlap gate edge cases", () => {
  const cmd = (over: Partial<CreateTimeEntryCommand> = {}): CreateTimeEntryCommand => ({
    techUserId: USER_ID,
    jobId: null,
    workDate: "2026-07-07",
    kind: "shop",
    startTime: "10:00",
    endTime: "22:00",
    note: "",
    src: "manual",
    running: false,
    ...over,
  });

  it("never clashes a retried create with its own already-landed row", async () => {
    const repo = new FakeTimeEntryRepository();
    // The first attempt landed; the retry carries the same client-authored id and times.
    repo.listRows.push(makeEntry({ id: CLIENT_ID as TimeEntryId, kind: "shop", startTime: "10:00", endTime: "22:00" }));
    repo.willReturn(makeEntry({ id: CLIENT_ID as TimeEntryId }));
    const useCase = new CreateTimeEntryUseCase(repo, new FixedClock(new Date("2026-07-07T08:00:00Z")), stubIds);

    const result = await useCase.exec(cmd({ id: CLIENT_ID }), ORG);

    // Not an overlap refusal — the duplicate id is the database's unambiguous problem to name.
    expect(isOk(result)).toBe(true);
  });

  it("refuses an inverted window BEFORE the gate, naming the actual problem", async () => {
    const repo = new FakeTimeEntryRepository();
    const useCase = new CreateTimeEntryUseCase(repo, new FixedClock(new Date("2026-07-07T08:00:00Z")), stubIds);

    const result = await useCase.exec(cmd({ startTime: "16:00", endTime: "08:00" }), ORG);

    expect(isOk(result)).toBe(false);
    if (!isOk(result)) expect(result.error.message).toContain("endTime must be after startTime");
    expect(repo.createCalls).toHaveLength(0);
  });

  it("ignores rows on a DIFFERENT day — the gate reads only the day being written", async () => {
    const repo = new FakeTimeEntryRepository();
    repo.listRows.push(makeEntry({ workDate: "2026-07-06", kind: "shop", startTime: "10:00", endTime: "22:00" }));
    repo.willReturn(makeEntry());
    const useCase = new CreateTimeEntryUseCase(repo, new FixedClock(new Date("2026-07-07T08:00:00Z")), stubIds);

    const result = await useCase.exec(cmd(), ORG);

    expect(isOk(result)).toBe(true);
  });

  it("refuses loudly when the day cannot be read in one page, rather than trusting page 1", async () => {
    const repo = new FakeTimeEntryRepository();
    repo.listNextCursor = "more";
    const useCase = new CreateTimeEntryUseCase(repo, new FixedClock(new Date("2026-07-07T08:00:00Z")), stubIds);

    const result = await useCase.exec(cmd(), ORG);

    expect(isOk(result)).toBe(false);
    if (!isOk(result)) expect(result.error.message).toContain("too many rows");
  });
});
