/**
 * Unit tests for CreateTimeEntryUseCase.
 *
 * Covers:
 *  - empty workDate validation error (guard branch)
 *  - id-minted branch: id generated by IdGenerator when cmd.id is absent
 *  - id-provided branch: cmd.id is forwarded as-is without minting
 *  - happy path: create called with correct payload, ok result returned, log side-effect
 */

import { describe, it, expect } from "vitest";
import {
  asOrgId,
  asUserId,
  asJobId,
  FixedClock,
  isOk,
} from "@mallet/shared/types";
import type { IdGenerator } from "@mallet/shared/ports";
import { TimeEntry, type TimeEntryProps } from "../domain/time-entry";
import type { TimeEntryRepository } from "../domain/time-entry-repository";
import type { TimeEntryId } from "@mallet/shared/types";
import { CreateTimeEntryUseCase, type CreateTimeEntryCommand } from "./create-time-entry";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ORG = asOrgId("22222222-2222-2222-2222-222222222222");
const USER_ID = asUserId("33333333-3333-3333-3333-333333333333");
const JOB_ID = asJobId("44444444-4444-4444-4444-444444444444");
const MINTED_ID = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
const CLIENT_ID = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const baseProps = (overrides: Partial<TimeEntryProps> = {}): TimeEntryProps => ({
  id: MINTED_ID as TimeEntryId,
  orgId: ORG,
  techUserId: USER_ID,
  jobId: null,
  workDate: "2026-07-07",
  kind: "job",
  startTime: "08:00",
  endTime: "10:00",
  note: "",
  src: "manual",
  status: "draft",
  running: false,
  approvedAt: null,
  createdAt: new Date("2026-07-07T08:00:00Z"),
  updatedAt: new Date("2026-07-07T08:00:00Z"),
  ...overrides,
});

const makeEntry = (overrides: Partial<TimeEntryProps> = {}): TimeEntry => {
  const result = TimeEntry.create(baseProps(overrides));
  if (!result.ok) throw new Error(`test setup: TimeEntry.create failed: ${JSON.stringify(result.error)}`);
  return result.value;
};

// ---------------------------------------------------------------------------
// Minimal in-memory fake for TimeEntryRepository
// ---------------------------------------------------------------------------

class FakeTimeEntryRepository implements TimeEntryRepository {
  readonly createCalls: Parameters<TimeEntryRepository["create"]>[0][] = [];
  private nextEntry: TimeEntry | null = null;

  /** Preload the TimeEntry the fake will return from create(). */
  willReturn(entry: TimeEntry): void {
    this.nextEntry = entry;
  }

  async create(input: Parameters<TimeEntryRepository["create"]>[0]): Promise<TimeEntry> {
    this.createCalls.push(input);
    if (!this.nextEntry) throw new Error("FakeTimeEntryRepository: call willReturn() first");
    const entry = this.nextEntry;
    this.nextEntry = null;
    return entry;
  }

  // Remaining interface methods — not exercised by create-time-entry
  async findById(): Promise<TimeEntry | null> {
    return null;
  }
  async list(): Promise<{ items: TimeEntry[]; nextCursor: null }> {
    return { items: [], nextCursor: null };
  }
  async save(): Promise<void> {
    // no-op
  }
  async remove(): Promise<number> {
    return 0;
  }
  async approveWeek(): Promise<number> {
    return 0;
  }
}

// Deterministic IdGenerator stub — always returns MINTED_ID.
const stubIds: IdGenerator = { newId: () => MINTED_ID };

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("CreateTimeEntryUseCase — workDate validation guard", () => {
  it("returns a validation error when workDate is an empty string", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: null,
      workDate: "",        // <- empty: triggers guard
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.kind).toBe("validation");
    if (result.error.kind === "validation") expect(result.error.field).toBe("workDate");
    // create() must never have been called
    expect(repo.createCalls).toHaveLength(0);
  });
});

describe("CreateTimeEntryUseCase — id-minted branch", () => {
  it("mints a new id when cmd.id is absent", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    repo.willReturn(makeEntry({ id: MINTED_ID as TimeEntryId }));

    const cmd: CreateTimeEntryCommand = {
      // id intentionally omitted
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    expect(repo.createCalls).toHaveLength(1);
    // The id forwarded to the repository must be the one minted by stubIds
    expect(repo.createCalls[0]?.id).toBe(MINTED_ID);
  });

  it("uses cmd.id when provided (does not mint)", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    repo.willReturn(makeEntry({ id: CLIENT_ID as TimeEntryId }));

    const cmd: CreateTimeEntryCommand = {
      id: CLIENT_ID,      // <- client-authored id
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    expect(repo.createCalls).toHaveLength(1);
    // The client-supplied id must reach the repository unchanged
    expect(repo.createCalls[0]?.id).toBe(CLIENT_ID);
  });
});

describe("CreateTimeEntryUseCase — happy path", () => {
  it("forwards the full payload to the repository and returns ok with the TimeEntry", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    const expectedEntry = makeEntry({
      id: MINTED_ID as TimeEntryId,
      orgId: ORG,
      techUserId: USER_ID,
      jobId: JOB_ID,
      workDate: "2026-07-07",
      kind: "travel",
      startTime: "09:00",
      endTime: "11:30",
      note: "drove to site",
      src: "clock",
      running: false,
    });
    repo.willReturn(expectedEntry);

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: JOB_ID,
      workDate: "2026-07-07",
      kind: "travel",
      startTime: "09:00",
      endTime: "11:30",
      note: "drove to site",
      src: "clock",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    if (!isOk(result)) return;

    // Returns the TimeEntry instance from the repo
    expect(result.value).toBeInstanceOf(TimeEntry);
    expect(result.value.props.workDate).toBe("2026-07-07");
    expect(result.value.props.kind).toBe("travel");
    expect(result.value.props.note).toBe("drove to site");

    // create was called exactly once
    expect(repo.createCalls).toHaveLength(1);
    const payload = repo.createCalls[0]!;
    expect(payload.orgId).toBe(ORG);
    expect(payload.techUserId).toBe(USER_ID);
    expect(payload.jobId).toBe(JOB_ID);
    expect(payload.workDate).toBe("2026-07-07");
    expect(payload.kind).toBe("travel");
    expect(payload.startTime).toBe("09:00");
    expect(payload.endTime).toBe("11:30");
    expect(payload.note).toBe("drove to site");
    expect(payload.src).toBe("clock");
    expect(payload.status).toBe("draft");
    expect(payload.running).toBe(false);
  });

  it("returns the TimeEntry returned by the repository (not a transformed copy)", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    const sentinel = makeEntry();
    repo.willReturn(sentinel);

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: "10:00",
      note: "",
      src: "manual",
      running: false,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    if (!isOk(result)) return;
    // Same reference — not a re-wrapped copy
    expect(result.value).toBe(sentinel);
  });

  it("passes running=true and null endTime through to the repository (running timer)", async () => {
    const repo = new FakeTimeEntryRepository();
    const clock = new FixedClock(new Date("2026-07-07T08:00:00Z"));
    const useCase = new CreateTimeEntryUseCase(repo, clock, stubIds);
    repo.willReturn(makeEntry({ endTime: null, running: true }));

    const cmd: CreateTimeEntryCommand = {
      techUserId: USER_ID,
      jobId: null,
      workDate: "2026-07-07",
      kind: "job",
      startTime: "08:00",
      endTime: null,
      note: "",
      src: "timer",
      running: true,
    };

    const result = await useCase.exec(cmd, ORG);

    expect(isOk(result)).toBe(true);
    expect(repo.createCalls).toHaveLength(1);
    expect(repo.createCalls[0]?.endTime).toBeNull();
    expect(repo.createCalls[0]?.running).toBe(true);
    expect(repo.createCalls[0]?.src).toBe("timer");
  });
});
