// Public surface for the pricebook module — the only sanctioned import seam.
export { createPricebookRouter } from "./api/pricebook-router";
export type { Service, ServiceProps } from "./domain/service";
export type { ServiceRepository } from "./domain/service-repository";
export type { Category, CategoryProps } from "./domain/category";
export type { CategoryRepository } from "./domain/category-repository";
export type { Material, MaterialProps } from "./domain/material";
export type { MaterialRepository } from "./domain/material-repository";
export type { ServiceMaterial, ServiceMaterialProps } from "./domain/service-material";
export type { ServiceMaterialRepository } from "./domain/service-material";
export { CreateServiceUseCase } from "./app/create-service";
export { UpdateServiceUseCase } from "./app/update-service";
export { ArchiveServiceUseCase } from "./app/archive-service";
export { ListServicesUseCase } from "./app/list-services";
export { CreateCategoryUseCase } from "./app/create-category";
export { ListCategoriesUseCase } from "./app/list-categories";
export { SeedPricebookUseCase } from "./app/seed-pricebook";
export type { SeedPricebookInput, SeedPricebookResult } from "./app/seed-pricebook";
export { CreateMaterialUseCase } from "./app/create-material";
export { UpdateMaterialUseCase } from "./app/update-material";
export { ArchiveMaterialUseCase } from "./app/archive-material";
export { ListMaterialsUseCase } from "./app/list-materials";
export { AttachMaterialUseCase } from "./app/attach-material";
export { DetachMaterialUseCase } from "./app/detach-material";
export { ListServiceMaterialsUseCase } from "./app/list-service-materials";
export { DrizzleServiceRepository } from "./infra/drizzle-service-repository";
export { DrizzleCategoryRepository } from "./infra/drizzle-category-repository";
export { DrizzleMaterialRepository } from "./infra/drizzle-material-repository";
export { DrizzleServiceMaterialRepository } from "./infra/drizzle-service-material-repository";
